services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:WQBYBX+D5623Lu5ic+xgcV7QdrcAnId3FbEWKG0GuAQ=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
    volumes:
      - .:/var/www
    working_dir: /var/www
